CREATE TABLE Authors
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(255) DEFAULT '',
		
	IsDeleted BIT NOT NULL DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME NULL,
	DeletedAt DATETIME NULL,
);

GO

CREATE TABLE LiteraryBooks
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Title VARCHAR(255) DEFAULT '',
	PublicationDate DATETIME DEFAULT GETDATE(),
		
	IsDeleted BIT NOT NULL DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME NULL,
	DeletedAt DATETIME NULL,
);

GO

CREATE TABLE AuthorBooks
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    AuthorId UNIQUEIDENTIFIER NOT NULL,
    LiteraryBookId UNIQUEIDENTIFIER NOT NULL,
	
	CreatedAt DATETIME DEFAULT GETDATE(),

	FOREIGN KEY (AuthorId) REFERENCES Authors(Id),
	FOREIGN KEY (LiteraryBookId) REFERENCES LiteraryBooks(Id),
	CONSTRAINT UC_AuthorBook UNIQUE (AuthorId, LiteraryBookId)
);

GO